name = input("Whats your name?")
print(name)
print("Hello",name + "!")
disposition = input("How are feeling today?")
print("Thats great! I'm have a great day today.")
age = input("By the way, how old are you?")
print(age + "?", "Wow your much younger than me!")
music = input("By the way what song are you listen to right now?")
print("I love",music +"! You have great taste in music! You can enjoy",music + " at www.applemusic.com")